// lp-tema-pg-01/src/components/layouts/MainLayout.vue
<script setup lang="ts">
import Navbar from "../fragments/Navbar.vue";
import Footer from "../fragments/Footer.vue";
import Hero from "../views/Hero.vue";
import About from "../views/About.vue";
import Service from "../views/Service.vue";
import Gallery from "../views/Gallery.vue";
import Contact from "../views/Contact.vue";
</script>

<template>
  <div class="w-full min-h-screen overflow-hidden bg-black">
    <Navbar />

    <main class="w-full">
      <Hero />
      <About />
      <Service />
      <Gallery />
      <Contact />
    </main>

    <Footer />
  </div>
</template>

// lp-tema-pariwisata-01/src/components/layouts/MainLayout.tsx
import Navbar from "../fragments/Navbar";
import Footer from "../fragments/Footer";

export default function MainLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex flex-col min-h-screen overflow-hidden">
      <Navbar />
      <main className="flex-grow">{children}</main>
      <Footer />
    </div>
  );
}
