// lp-tema-pg-01/src/components/layouts/MainLayout.vue
<script setup lang="ts">
import Navbar from "../fragments/Navbar.vue";
import Footer from "../fragments/Footer.vue";
import Hero from "../views/Hero.vue";
import About from "../views/About.vue";
import Service from "../views/Service.vue";
import Gallery from "../views/Gallery.vue";
import Contact from "../views/Contact.vue";
</script>

<template>
  <div class="w-full min-h-screen overflow-hidden bg-black">
    <Navbar />

    <main class="w-full">
      <Hero />
      <About />
      <Service />
      <Gallery />
      <Contact />
    </main>

    <Footer />
  </div>
</template>

// lp-tema-fnb-02/src/components/layouts/MainLayout.tsx
import Navbar from "../fragments/Navbar";
import Footer from "../fragments/Footer";
import type { ReactNode } from "react";

interface MainLayoutProps {
  children: ReactNode;
}

const MainLayout = ({ children }: MainLayoutProps) => {
  return (
    <div className="min-h-screen overflow-hidden bg-gray-50">
      <Navbar />
      <main>{children}</main>
      <Footer />
    </div>
  );
};

export default MainLayout;
